# Generated by Django 4.2.7 on 2023-11-12 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0002_delete_imagevideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='categories',
        ),
    ]
