# Generated by Django 4.2.7 on 2023-11-14 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0003_remove_location_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='locations',
            new_name='location',
        ),
    ]
