# Generated by Django 4.2.7 on 2023-11-15 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0004_rename_locations_tour_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='location',
        ),
        migrations.AddField(
            model_name='tour',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drfapp.location'),
        ),
    ]
